//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flow.Plugin.VSCodeWorkspaces.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flow.Plugin.VSCodeWorkspaces.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discover Remote Machines 的本地化字符串。
        /// </summary>
        public static string DiscoverMachines {
            get {
                return ResourceManager.GetString("DiscoverMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically discover remote machines configured in settings.json. 的本地化字符串。
        /// </summary>
        public static string DiscoverMachinesTooltip {
            get {
                return ResourceManager.GetString("DiscoverMachinesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discover Workspaces 的本地化字符串。
        /// </summary>
        public static string DiscoverWorkspaces {
            get {
                return ResourceManager.GetString("DiscoverWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically discover workspaces (folders) from recent opened list of VSCode. 的本地化字符串。
        /// </summary>
        public static string DiscoverWorkspacesTooltip {
            get {
                return ResourceManager.GetString("DiscoverWorkspacesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Folder URI 的本地化字符串。
        /// </summary>
        public static string ExtraFolderUri {
            get {
                return ResourceManager.GetString("ExtraFolderUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 in 的本地化字符串。
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open folder in default file manager 的本地化字符串。
        /// </summary>
        public static string OpenFolderSubTitle {
            get {
                return ResourceManager.GetString("OpenFolderSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opens workspaces, remote machines (SSH or Codespaces) and containers, previously opened in VS Code. 的本地化字符串。
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Studio Code Workspaces 的本地化字符串。
        /// </summary>
        public static string PluginTitle {
            get {
                return ResourceManager.GetString("PluginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSH remote machine 的本地化字符串。
        /// </summary>
        public static string SSHRemoteMachine {
            get {
                return ResourceManager.GetString("SSHRemoteMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container 的本地化字符串。
        /// </summary>
        public static string TypeWorkspaceContainer {
            get {
                return ResourceManager.GetString("TypeWorkspaceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dev Container 的本地化字符串。
        /// </summary>
        public static string TypeWorkspaceDevContainer {
            get {
                return ResourceManager.GetString("TypeWorkspaceDevContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        public static string TypeWorkspaceLocal {
            get {
                return ResourceManager.GetString("TypeWorkspaceLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workspace 的本地化字符串。
        /// </summary>
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
    }
}
